// ***
// This code is auto-generated by a build tool. Any changes made manually will be lost
// the next time this code is regenerated.
// ***


using System;
using System.Reflection;
using System.Runtime.CompilerServices;


[assembly: InternalsVisibleTo("RazorSoft.Media.Runtime")]

[assembly: AssemblyCompany("RazorSoft Media, LLC")]
[assembly: AssemblyConfiguration("Debug")]
[assembly: AssemblyCopyright("2022 RazorSoft Media, LLC")]
[assembly: AssemblyProduct("RazorSoft.Media.Framework")]
[assembly: AssemblyTitle("RazorSoft.Media")]

/*
    Version schema:
        Major                   -   Increment on changes that break backward compatibility
        Minor                   -   Increment on every release
        Revision                -   Increment at the start of sprint, feature, project, etc.
        DaysSinceRevision       -   Number of days since Revision was officially incremented
* ***/

//  this is for the NuGet package ...???
#if DEBUG
    [assembly: AssemblyFileVersion("0.3.0.42")]
    [assembly: AssemblyVersion("0.3.0.42")]
#elif !DEBUG
    [assembly: AssemblyFileVersion("0.3.42.56")]
    [assembly: AssemblyVersion("0.3.42.56")]
    [assembly: AssemblyInformationalVersion("0.3.42.56")]
    [assembly: ObfuscateAssembly(false)]
#endif

namespace RazorSoft.Media {

    public static class AssemblyInfo {

#if DEBUG
        private static readonly string asmVersion = "0.3.0.42";
#elif !DEBUG
        private static readonly string asmVersion = "0.3.42.56";
#endif

        public static string AssemblyVersion => asmVersion;
    }
}

