// 
// This code is auto-generated by a build tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 


using System;
using System.Reflection;
using System.Runtime.CompilerServices;


//[assembly: InternalsVisibleTo("SharpGLX.Windows")]

[assembly: AssemblyCompany("RazorSoft Media, LLC")]
[assembly: AssemblyCopyright("2022 RazorSoft Media, LLC")]
[assembly: AssemblyProduct("RazorSoft.SharpGLX.Media")]
[assembly: AssemblyTitle("RazorSoft.SharpGLX.Media")]

/*
    Version schema:
        Major                   -   Increment on changes that break backward compatibility
        Minor                   -   Increment on every release
        Revision                -   Increment at the start of sprint, feature, project, etc.
        DaysSinceRevision       -   Number of days since Revision was officially incremented
* ***/

//  this is for the NuGet package ...???
#if DEBUG
    [assembly: AssemblyFileVersion("0.2.0.0")]
    [assembly: AssemblyVersion("0.2.0.0")]
#elif !DEBUG
    [assembly: AssemblyFileVersion("0.2.0.0")]
    [assembly: AssemblyVersion("0.2.0.0")]
    [assembly: AssemblyInformationalVersion("0.2.0.0")]
    [assembly: ObfuscateAssembly(false)]
#endif

