// 
// This code is auto-generated by a build tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 


using System;
using System.Reflection;
using System.Runtime.CompilerServices;


[assembly: InternalsVisibleTo("SharpGLX.Windows")]

//[assembly: AssemblyCompany("RazorSoft Media, LLC")]
//[assembly: AssemblyCopyright("2022 RazorSoft Media, LLC")]
[assembly: AssemblyProduct("SharpGLX")]
[assembly: AssemblyTitle("SharpGLX")]

/*
    Version schema:
        Major                   -   Increment on changes that break backward compatibility
        Minor                   -   Increment on every release
        Revision                -   Increment at the start of sprint, feature, project, etc.
        DaysSinceRevision       -   Number of days since Revision was officially incremented
* ***/

//  this is for the NuGet package ...???
#if DEBUG
    [assembly: AssemblyFileVersion("0.1.0.11")]
    [assembly: AssemblyVersion("0.1.0.11")]
#elif !DEBUG
    [assembly: AssemblyFileVersion("0.1.11.3")]
    [assembly: AssemblyVersion("0.1.11.3")]
    [assembly: AssemblyInformationalVersion("0.1.11.3")]
    [assembly: ObfuscateAssembly(false)]
#endif

