// 
// This code is auto-generated by a build tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 


using System;
using System.Reflection;
using System.Runtime.CompilerServices;


[assembly: InternalsVisibleTo("RazorSoft.Media.Runtime")]
[assembly: InternalsVisibleTo("RazorSoft.Media.Framework")]

[assembly: AssemblyCompanyAttribute("RazorSoft Media, LLC")]
[assembly: AssemblyConfigurationAttribute("Debug")]
[assembly: AssemblyCopyrightAttribute("2022 RazorSoft Media, LLC")]
[assembly: AssemblyProductAttribute("RazorSoft.Media.Runtime.Domain")]
[assembly: AssemblyTitleAttribute("RazorSoft.Media")]

/*
    Version schema:
        Major                   -   Increment on changes that break backward compatibility
        Minor                   -   Increment on every release
        Revision                -   Increment at the start of sprint, feature, project, etc.
        DaysSinceRevision       -   Number of days since Revision was officially incremented
* ***/

//  this is for the NuGet package ...???
#if DEBUG
    [assembly: AssemblyFileVersion("0.0.1.53")]
    [assembly: AssemblyVersion("0.0.1.53")]
#elif !DEBUG
    [assembly: AssemblyFileVersion("0.0.53.89")]
    [assembly: AssemblyVersion("0.0.53.89")]
    [assembly: AssemblyInformationalVersion("0.0.53.89")]
    [assembly: ObfuscateAssembly(false)]
#endif

